name: publishing

on:
  push:
    branches:
      - master

env:
  GITHUB_TOKEN: ${{ secrets.github_token }}

jobs:
  setup:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        id: cache
        with:
          path: sites/landing/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('sites/landing/package-lock.json') }}
      - uses: actions/setup-node@v1
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          node-version: 12.x
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm install
  publish:
    needs: setup
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: sites/landing/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('sites/landing/package-lock.json') }}
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Prepare git environment
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: Build and publish site
        run: |
          bin/publish.sh
